root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml", "yml"]
exclude_dir = [
  "logs",
  "tmp",
  "build",
  "vendor",
  ".git"
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 500
stop_on_error = true
send_interrupt = true
kill_delay = 500
pre_cmd = [
  "go vet ./...",
  "GOFLAGS='-buildvcs=false' golangci-lint run ./...",
]
[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true